name: Update rust-toolchain

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * 1" # 3:30 on Monday

jobs:
  update-rust-toolchain:
    name: Update Rust toolchain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@2289ae9c945707079a248f5e4f5743a6592429ef # v2.90.0

      - name: Update rust version inside of rust-toolchain file
        id: update_rust_toolchain
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPDATECLI_GITHUB_OWNER: ${{ github.repository_owner }}
        run: |-
          updatecli apply --config ./updatecli/updatecli.d/update-rust-toolchain.yaml \
                    --values updatecli/values.yaml
